

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(primer.data)
library(tidyverse)
library(readxl)
library(janitor)
library(ggplot2)
library(ggthemes)
```

## R Markdown

```{r}
raw_data <- read_excel("/Users/Nansi/Desktop/Gov_1005/Classwork_day_6/raw_data/class_enrollment_summary_by_term_2-11-2021.xlsx", skip = 3) %>% 
clean_names()
```


```{r}
raw_data_clean<- raw_data %>%
   arrange(desc(total)) %>%
   select("course_id", "course_name", "total") %>% 
   drop_na()

 # this data set had many columns so it was essential to narrow down the
 # information to the categories that we are focusing on

```



```{r}
enrollment_p <- raw_data_clean %>% 
  group_by(course_id, course_name) %>% 
  summarize(enrollment = sum(total),
            .groups = "drop") %>% 
  arrange(desc(enrollment)) %>% 
  slice(1:10) %>% 
  ggplot(mapping = aes(x = fct_reorder(course_name, enrollment),
                       y = enrollment)) +
         geom_col( fill = "darkred") +
   labs(title = "10 Most Popular Courses at Harvard",
        subtitle = "Spring 2021",
        caption = "Harvard Registrar",
        x = NULL,
        y = "Total Enrollment") +
  coord_flip() +
  theme_economist() 
 
 enrollment_p 
  
```



```{r}
ggsave(filename = "enrollment.jpg", enrollment_p)
```

